volumes:
  mariarpg:
    #déclaration du volume pour la base

services:

  # container de bdd
  rpgbase:
    #nom de service
    container_name: baserpg
    image: mariadb:latest
    ports:
      - '3307:3306'
    volumes:
      - mariarpg:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: rpgadmin
      MYSQL_DATABASE: rpg
      MYSQL_USER: rpguser
      MYSQL_PASSWORD: rpguser

  # container php
  rpgphp:
    container_name: phprpg
    build:
      context: ./php
    #    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '9001:9000'
    environment:
      DEBUG: '1'
      PHP_DISPLAY_ERRORS: '1'
      PHP_POST_MAX_SIZE: "100M"
      PHP_UPLOAD_MAX_FILESIZE: "100M"
      TZ: UTC
    volumes:
      - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - rpgbase

  # server web
  rpgnginx:
    container_name: nginxrpg
    image: nginx:stable-alpine
    #    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      TZ: UTC
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx/
    depends_on:
      - rpgphp
      - rpgbase
