<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Une erreur est survenue - Autodingo.com</title>
</head>
<body>
    <h1>Erreur serveur - 500</h1>
    <p>
        Quelque chose a disfonctionné et le serveur a pris feu.<br>
        Désolé vous ne pouvez pas encore louer cette magnifique Traban de 1950.
    </p>   
</body>
</html>